# Generated by Django 6.0.3 on 2026-03-30 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessamentoPCP',
            fields=[
                ('id', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, verbose_name='PID')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Arquivo Original')),
                ('lote', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número do Lote')),
                ('total_pecas', models.PositiveIntegerField(default=0, verbose_name='Total de Peças')),
                ('arquivo_saida', models.FileField(blank=True, null=True, upload_to='pcp/outputs/%Y/%m/%d/', verbose_name='Roteiro Gerado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Processado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Processamento PCP',
                'verbose_name_plural': 'Processamentos PCP',
                'ordering': ['-criado_em'],
            },
        ),
    ]
