# Generated by Django 6.0.3 on 2026-04-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pcp", "0002_alter_processamentopcp_criado_em_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processamentopcp",
            name="data_liberacao",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data de Liberação"
            ),
        ),
        migrations.AddField(
            model_name="processamentopcp",
            name="data_liberacao_viagem",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data de Liberação Viagem"
            ),
        ),
        migrations.AddField(
            model_name="processamentopcp",
            name="liberado_para_bipagem",
            field=models.BooleanField(
                default=False, verbose_name="Liberado para Bipagem"
            ),
        ),
        migrations.AddField(
            model_name="processamentopcp",
            name="liberado_para_viagem",
            field=models.BooleanField(
                default=False, verbose_name="Liberado para Viagem"
            ),
        ),
    ]
