# Generated by Django 6.0.3 on 2026-04-04 23:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pcp", "0003_processamentopcp_data_liberacao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LotePCP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_por", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "atualizado_por",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("pid", models.CharField(editable=False, max_length=8, unique=True)),
                ("arquivo_original", models.CharField(max_length=255)),
                ("data_processamento", models.DateTimeField(auto_now_add=True)),
                ("cliente_nome", models.CharField(max_length=255)),
                (
                    "cliente_id_projeto",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "ordem_producao",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_producao", "Em Produção"),
                            ("finalizado", "Finalizado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote PCP",
                "verbose_name_plural": "Lotes PCP",
                "ordering": ["-data_processamento"],
            },
        ),
        migrations.CreateModel(
            name="AmbientePCP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_por", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "atualizado_por",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ambientes",
                        to="pcp.lotepcp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ambiente PCP",
                "verbose_name_plural": "Ambientes PCP",
                "unique_together": {("lote", "nome")},
            },
        ),
        migrations.CreateModel(
            name="ModuloPCP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_por", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "atualizado_por",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "codigo_modulo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "ambiente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modulos",
                        to="pcp.ambientepcp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Módulo PCP",
                "verbose_name_plural": "Módulos PCP",
                "unique_together": {("ambiente", "codigo_modulo", "nome")},
            },
        ),
        migrations.CreateModel(
            name="PecaPCP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_por", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "atualizado_por",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("referencia_bruta", models.CharField(max_length=100)),
                (
                    "codigo_modulo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("codigo_peca", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
                ("local", models.CharField(blank=True, max_length=100, null=True)),
                ("material", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "codigo_material",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "comprimento",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "largura",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "espessura",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "metro_quadrado",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=12, null=True
                    ),
                ),
                ("quantidade_planejada", models.PositiveIntegerField()),
                ("atributos_tecnicos", models.JSONField(blank=True, default=dict)),
                ("roteiro", models.TextField(blank=True, null=True)),
                ("plano", models.CharField(blank=True, max_length=2, null=True)),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "lote_dinabox",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "id_peca_dinabox",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("quantidade_produzida", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_producao", "Em Produção"),
                            ("finalizado", "Finalizado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                (
                    "modulo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pecas",
                        to="pcp.modulopcp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Peça PCP",
                "verbose_name_plural": "Peças PCP",
                "ordering": ["codigo_peca"],
            },
        ),
    ]
