# Generated by Django 6.0.3 on 2026-04-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pcp", "0005_auditoriaprocessamentopcp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processamentopcp",
            name="data_liberacao",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data de Liberacao"
            ),
        ),
        migrations.AlterField(
            model_name="processamentopcp",
            name="data_liberacao_viagem",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data de Liberacao Viagem"
            ),
        ),
        migrations.AlterField(
            model_name="processamentopcp",
            name="lote",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Numero do Lote"
            ),
        ),
        migrations.AlterField(
            model_name="processamentopcp",
            name="total_pecas",
            field=models.PositiveIntegerField(default=0, verbose_name="Total de Pecas"),
        ),
    ]
