# Generated by Django 5.2.13 on 2026-04-20 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0006_alter_processamentopcp_data_liberacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaRoteamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_peca', models.CharField(db_index=True, max_length=100)),
                ('tipo_transformacao', models.CharField(choices=[('consolidacao', 'Consolidação de Ripas'), ('roteiro', 'Cálculo de Roteiro'), ('plano', 'Determinação de Plano'), ('validacao', 'Validação')], max_length=50)),
                ('valor_antes', models.TextField(blank=True)),
                ('valor_depois', models.TextField(blank=True)),
                ('regra_aplicada', models.CharField(max_length=200)),
                ('confianca', models.CharField(default='high', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='pcp.processamentopcp')),
            ],
            options={
                'verbose_name': 'Auditoria de Roteamento',
                'verbose_name_plural': 'Auditorias de Roteamento',
                'ordering': ['-criado_em'],
            },
        ),
    ]
