# Generated by Django 6.0.3 on 2026-04-01 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estoque", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produto",
            options={
                "ordering": ["categoria__nome", "nome"],
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
        migrations.AddField(
            model_name="produto",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AddField(
            model_name="produto",
            name="atributos_especificos",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Atributos específicos"
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="localizacao",
            field=models.CharField(
                blank=True,
                help_text="Ex: Prateleira A-03, Gaveta Dobradiças",
                max_length=100,
                null=True,
                verbose_name="Localização no almoxarifado",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="lote",
            field=models.CharField(
                blank=True,
                help_text="Importante para rastreabilidade (NF, lote do fornecedor...)",
                max_length=100,
                null=True,
                verbose_name="Lote / Referência",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="preco_custo",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Preço de custo",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="unidade_medida",
            field=models.CharField(
                choices=[
                    ("un", "Unidade"),
                    ("pc", "Peça"),
                    ("m", "Metro linear"),
                    ("m2", "Metro quadrado"),
                    ("kg", "Quilograma"),
                    ("cx", "Caixa"),
                    ("l", "Litro"),
                ],
                default="un",
                max_length=20,
                verbose_name="Unidade de medida",
            ),
        ),
        migrations.CreateModel(
            name="CategoriaProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=120, verbose_name="Nome da Categoria"),
                ),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcategorias",
                        to="estoque.categoriaproduto",
                        verbose_name="Categoria Pai",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Produto",
                "verbose_name_plural": "Categorias de Produtos",
                "ordering": ["ordem", "nome"],
                "unique_together": {("nome", "parent")},
            },
        ),
        migrations.AddField(
            model_name="produto",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="produtos",
                to="estoque.categoriaproduto",
                verbose_name="Categoria",
            ),
            preserve_default=False,
        ),
    ]
