# Generated by Django 6.0.3 on 2026-04-04 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bipagem", "0002_eventobipagem_erro_sincronia_pedido_data_conclusao_and_more"),
        ("estoque", "0003_alter_categoriaproduto_id_alter_movimentacao_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reserva",
            name="projeto",
        ),
        migrations.AddField(
            model_name="reserva",
            name="pedido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas",
                to="bipagem.pedido",
                verbose_name="Pedido/Projeto",
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="projeto_legado",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Projeto (Legado)"
            ),
        ),
        migrations.AlterField(
            model_name="categoriaproduto",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
