# Generated by Django 6.0.3 on 2026-04-04 02:39

import apps.estoque.domain.tipos
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estoque", "0004_remove_reserva_projeto_reserva_pedido_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriaproduto",
            name="familia",
            field=models.CharField(
                choices=[
                    ("mdf", "Mdf"),
                    ("ferragens", "Ferragens"),
                    ("fitas_borda", "Fitas Borda"),
                    ("quimicos_insumos", "Quimicos Insumos"),
                    ("vidros_espelhos", "Vidros Espelhos"),
                    ("embalagens", "Embalagens"),
                    ("epis_ferramentas", "Epis Ferramentas"),
                    ("outros", "Outros"),
                ],
                default=apps.estoque.domain.tipos.FamiliaProduto["OUTROS"],
                max_length=30,
                verbose_name="Família de Produto",
            ),
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="espessura",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Espessura (MDF)"
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="espessura",
            field=models.IntegerField(
                blank=True,
                help_text="Apenas para produtos da família MDF",
                null=True,
                verbose_name="Espessura (MDF)",
            ),
        ),
        migrations.CreateModel(
            name="SaldoMDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("espessura", models.IntegerField(verbose_name="Espessura (mm)")),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantidade em estoque"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saldos_mdf",
                        to="estoque.produto",
                        verbose_name="Produto (MDF)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saldo MDF",
                "verbose_name_plural": "Saldos MDF",
                "ordering": ["produto", "espessura"],
                "unique_together": {("produto", "espessura")},
            },
        ),
    ]
