# Generated by Django 6.0.3 on 2026-04-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estoque", "0005_categoriaproduto_familia_movimentacao_espessura_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saldomdf",
            name="preco_custo",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Preço de custo (Chapa)",
            ),
        ),
    ]
