# Generated by Django 6.0.3 on 2026-04-06 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_reserva_contexto_pcp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reserva',
            new_name='estoque_res_status_5bf58c_idx',
            old_name='estoque_res_status_87f295_idx',
        ),
        migrations.RenameIndex(
            model_name='reserva',
            new_name='estoque_res_lote_pc_09341a_idx',
            old_name='estoque_res_lote_pcp_idx',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='espessura',
            field=models.IntegerField(blank=True, help_text='Apenas para produtos da familia MDF', null=True, verbose_name='Espessura (MDF)'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observacao'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
