# Generated by Django 5.2.12 on 2026-04-04 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0003_alter_categoriaproduto_id_alter_movimentacao_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapeamentoMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dinabox', models.CharField(help_text='Exatamente como aparece no CSV/HTML do Dinabox', max_length=255, unique=True, verbose_name='Nome no Dinabox')),
                ('fator_conversao', models.DecimalField(decimal_places=4, default=1.0, help_text='Multiplicador para o consumo (ex: 1.1 para 10% de margem de erro/perda)', max_digits=10, verbose_name='Fator de Conversão')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeamentos', to='estoque.produto', verbose_name='Produto Vinculado')),
            ],
            options={
                'verbose_name': 'Mapeamento de Material',
                'verbose_name_plural': 'Mapeamentos de Materiais',
            },
        ),
    ]
