# Generated by Django 6.0.3 on 2026-04-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0002_alter_mapeamentomaterial_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinaboxClienteIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_name_normalized', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('customer_type', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('customer_status', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('customer_emails_text', models.TextField(blank=True, default='')),
                ('customer_phones_text', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Indice Cliente Dinabox',
                'verbose_name_plural': 'Indices de Clientes Dinabox',
                'indexes': [models.Index(fields=['customer_name_normalized'], name='dinabox_cli_nome_idx'), models.Index(fields=['customer_status', 'customer_type'], name='dinabox_cli_st_tp_idx'), models.Index(fields=['synced_at'], name='dinabox_cli_sync_idx')],
            },
        ),
    ]
