# Generated by Django 6.0.3 on 2026-04-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "estoque",
            "0009_rename_estoque_res_status_87f295_idx_estoque_res_status_5bf58c_idx_and_more",
        ),
        ("integracoes", "0003_dinaboxclienteindex"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dinaboxclienteindex",
            options={
                "verbose_name": "Índice Cliente Dinabox",
                "verbose_name_plural": "Índices de Clientes Dinabox",
            },
        ),
        migrations.AlterField(
            model_name="dinaboxclienteindex",
            name="customer_emails_text",
            field=models.TextField(
                blank=True, default="", verbose_name="Emails (texto)"
            ),
        ),
        migrations.AlterField(
            model_name="dinaboxclienteindex",
            name="customer_id",
            field=models.CharField(
                db_index=True,
                max_length=64,
                unique=True,
                verbose_name="ID do Cliente Dinabox",
            ),
        ),
        migrations.AlterField(
            model_name="dinaboxclienteindex",
            name="customer_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Nome do Cliente"
            ),
        ),
        migrations.AlterField(
            model_name="dinaboxclienteindex",
            name="customer_name_normalized",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=255,
                verbose_name="Nome Normalizado (para busca)",
            ),
        ),
        migrations.AlterField(
            model_name="dinaboxclienteindex",
            name="customer_phones_text",
            field=models.TextField(
                blank=True, default="", verbose_name="Telefones (texto)"
            ),
        ),
        migrations.AlterField(
            model_name="dinaboxclienteindex",
            name="customer_status",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=16,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="dinaboxclienteindex",
            name="customer_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=16,
                verbose_name="Tipo (PF/PJ)",
            ),
        ),
        migrations.AlterField(
            model_name="dinaboxclienteindex",
            name="raw_payload",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Payload Bruto (Dinabox)"
            ),
        ),
        migrations.AlterField(
            model_name="dinaboxclienteindex",
            name="synced_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="Última Sincronização"
            ),
        ),
        migrations.AlterField(
            model_name="mapeamentomaterial",
            name="nome_dinabox",
            field=models.CharField(
                help_text="Exatamente como aparece no JSON/CSV do Dinabox",
                max_length=255,
                unique=True,
                verbose_name="Nome no Dinabox",
            ),
        ),
        migrations.AddIndex(
            model_name="mapeamentomaterial",
            index=models.Index(fields=["nome_dinabox"], name="mapeamento_nome_idx"),
        ),
        migrations.AddIndex(
            model_name="mapeamentomaterial",
            index=models.Index(fields=["ativo"], name="mapeamento_ativo_idx"),
        ),
    ]
