# Generated by Django 4.2.29 on 2026-04-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integracoes", "0004_alter_dinaboxclienteindex_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DinaboxImportacaoProjeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Project ID"
                    ),
                ),
                (
                    "project_customer_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="Customer ID",
                    ),
                ),
                (
                    "project_description",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=255,
                        verbose_name="Descricao do Projeto",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PROCESSANDO", "Processando"),
                            ("CONCLUIDO", "Concluido"),
                            ("ERRO", "Erro"),
                        ],
                        db_index=True,
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                ("tentativas", models.PositiveIntegerField(default=0)),
                (
                    "prioridade",
                    models.PositiveSmallIntegerField(db_index=True, default=100),
                ),
                (
                    "origem",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Origem"
                    ),
                ),
                ("payload_bruto", models.JSONField(blank=True, default=dict)),
                ("resultado_resumo", models.JSONField(blank=True, default=dict)),
                ("ultimo_erro", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("iniciado_em", models.DateTimeField(blank=True, null=True)),
                ("concluido_em", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Importacao Projeto Dinabox",
                "verbose_name_plural": "Importacoes de Projetos Dinabox",
                "ordering": ["prioridade", "criado_em"],
                "indexes": [
                    models.Index(
                        fields=["status", "prioridade", "criado_em"],
                        name="din_imp_st_pr_cr_idx",
                    ),
                    models.Index(
                        fields=["project_id", "status"], name="din_imp_proj_st_idx"
                    ),
                ],
            },
        ),
    ]
