"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-x_8kz%w)*%opcd2w(omx^po)&(+sn&tbn*3q^mch_v8ay+(c5c"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

_allowed_hosts_env = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]

# MVP: permitir hosts arbitrários quando DEBUG estiver ligado.
# (para produção, ajuste DJANGO_ALLOWED_HOSTS e desative DEBUG)
if DEBUG:
    ALLOWED_HOSTS = _allowed_hosts_env or ["*"]
else:
    ALLOWED_HOSTS = _allowed_hosts_env


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'apps.core',
    'apps.estoque',
    'apps.pcp',
    'apps.bipagem',
    'apps.integracoes',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

PCP_OUTPUTS_DIR = BASE_DIR / 'media' / 'pcp' / 'outputs'
MEDIA_ROOT = BASE_DIR / 'media'


MEDIA_URL = '/media/'

# ── AUTENTICAÇÃO ──────────────────────────────────────────────
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
 
# ── FUSO HORÁRIO (Brasil) ──────────────────────────────────────
def _env_bool(name: str, default: str = "0") -> bool:
    return os.getenv(name, default).strip().lower() in {"1", "true", "yes", "on"}


PCP_BLOQUEAR_LIBERACAO_COM_RISCO_ESTOQUE = _env_bool(
    "PCP_BLOQUEAR_LIBERACAO_COM_RISCO_ESTOQUE",
    "0",
)
PCP_ESTOQUE_RISCO_JANELA_DIAS = int(os.getenv("PCP_ESTOQUE_RISCO_JANELA_DIAS", "30"))

# ── INTEGRACAO DINABOX (TESTES) ─────────────────────────────────
DINABOX_BASE_URL = os.getenv("DINABOX_BASE_URL", "https://www.dinabox.app")
DINABOX_SERVICE_USERNAME = os.getenv("DINABOX_SERVICE_USERNAME", "80385122")
DINABOX_SERVICE_PASSWORD = os.getenv("DINABOX_SERVICE_PASSWORD", "abacatudo.renara.123")
DINABOX_TIMEOUT_SECONDS = int(os.getenv("DINABOX_TIMEOUT_SECONDS", "15"))
DINABOX_VERIFY_SSL = _env_bool("DINABOX_VERIFY_SSL", "1")

LANGUAGE_CODE = "pt-br"
TIME_ZONE = "America/Sao_Paulo"
 

# ── PCP PIPELINE ──────────────────────────────────────────────
USE_NEW_PCP_PIPELINE = True
