# Generated by Django 6.0.3 on 2026-04-03 01:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrdemProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_ambiente", models.CharField(max_length=255)),
                ("referencia_principal", models.CharField(blank=True, max_length=100)),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Ordem de Produção",
                "verbose_name_plural": "Ordens de Produção",
                "ordering": ["nome_ambiente"],
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_pedido",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("cliente_nome", models.CharField(db_index=True, max_length=255)),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_importacao", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="Modulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referencia_modulo", models.CharField(db_index=True, max_length=100)),
                ("nome_modulo", models.CharField(max_length=255)),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "ordem_producao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modulos",
                        to="bipagem.ordemproducao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Módulo",
                "verbose_name_plural": "Módulos",
                "ordering": ["referencia_modulo"],
                "unique_together": {("ordem_producao", "referencia_modulo")},
            },
        ),
        migrations.CreateModel(
            name="Peca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_peca", models.CharField(db_index=True, max_length=50)),
                (
                    "numero_lote_pcp",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("local", models.CharField(db_index=True, max_length=100)),
                ("material", models.CharField(blank=True, max_length=255)),
                ("largura_mm", models.FloatField(blank=True, null=True)),
                ("altura_mm", models.FloatField(blank=True, null=True)),
                ("espessura_mm", models.FloatField(blank=True, null=True)),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("roteiro", models.TextField(blank=True)),
                ("plano_corte", models.CharField(blank=True, max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("BIPADA", "Bipada"),
                            ("CONCLUIDA", "Concluída"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        db_index=True,
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                ("data_bipagem", models.DateTimeField(blank=True, null=True)),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pecas",
                        to="bipagem.modulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Peça",
                "verbose_name_plural": "Peças",
                "ordering": ["id_peca"],
                "unique_together": {("modulo", "id_peca")},
            },
        ),
        migrations.AddField(
            model_name="ordemproducao",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordens_producao",
                to="bipagem.pedido",
            ),
        ),
        migrations.CreateModel(
            name="EventoBipagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("momento", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("usuario", models.CharField(default="SISTEMA", max_length=100)),
                ("localizacao", models.CharField(blank=True, max_length=100)),
                (
                    "peca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bipagens",
                        to="bipagem.peca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Bipagem",
                "verbose_name_plural": "Eventos de Bipagem",
                "ordering": ["-momento"],
                "indexes": [
                    models.Index(
                        fields=["peca", "momento"],
                        name="bipagem_eve_peca_id_3ec78b_idx",
                    )
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="ordemproducao",
            unique_together={("pedido", "nome_ambiente")},
        ),
    ]
