# Generated by Django 6.0.3 on 2026-04-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bipagem", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventobipagem",
            name="erro_sincronia",
            field=models.TextField(
                blank=True,
                help_text="Erro ao tentar abater estoque automaticamente",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="data_conclusao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="data_entrega_prevista",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="observacoes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("ORCAMENTO", "Orçamento"),
                    ("APROVADO", "Aprovado"),
                    ("PCP", "Em PCP"),
                    ("PRODUCAO", "Em Produção"),
                    ("EXPEDICAO", "Em Expedição"),
                    ("ENTREGUE", "Entregue"),
                    ("CANCELADO", "Cancelado"),
                ],
                db_index=True,
                default="APROVADO",
                max_length=20,
            ),
        ),
    ]
