# Generated by Django 6.0.3 on 2026-04-04 02:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bipagem", "0002_eventobipagem_erro_sincronia_pedido_data_conclusao_and_more"),
        (
            "bipagem",
            "0002_peca_destino_alter_eventobipagem_id_alter_modulo_id_and_more",
        ),
    ]

    operations = []
