# Generated by Django 6.0.3 on 2026-04-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bipagem", "0004_alter_eventobipagem_id_alter_modulo_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="bloqueado",
            field=models.BooleanField(default=False, verbose_name="Bipagem Bloqueada"),
        ),
    ]
