# Generated by Django 5.0.14 on 2026-04-04 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bipagem', '0005_pedido_bloqueado'),
        ('pcp', '0003_processamentopcp_data_liberacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventobipagem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='LoteProducao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50, unique=True, verbose_name='Número do Lote')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('liberado_para_bipagem', models.BooleanField(default=False, verbose_name='Liberado para Bipagem')),
                ('bloqueado_motivo', models.TextField(blank=True, null=True, verbose_name='Motivo do Bloqueio')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('processamento_pcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_producao', to='pcp.processamentopcp', verbose_name='Processamento PCP')),
            ],
            options={
                'verbose_name': 'Lote de Produção',
                'verbose_name_plural': 'Lotes de Produção',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='peca',
            name='lote_producao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pecas', to='bipagem.loteproducao', verbose_name='Lote de Produção'),
        ),
    ]
