# Generated by Django 6.0.3 on 2026-04-05 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bipagem", "0008_recria_eventobipagem_pcp"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="eventobipagem",
            new_name="bipagem_eve_peca_id_3ec78b_idx",
            old_name="bipagem_eve_peca_id_0d64d9_idx",
        ),
    ]
